/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json;
    using System.Runtime.Serialization;
    using System.Text;

    /// <summary>
    /// Backup team called in, may be null.
    /// </summary>
    [DataContract]
    public partial class EliminationAllianceBackup : IEquatable<EliminationAllianceBackup>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EliminationAllianceBackup" /> class.
        /// </summary>
        /// <param name="_in">Team key that was called in as the backup..</param>
        /// <param name="_out">Team key that was replaced by the backup team..</param>
        public EliminationAllianceBackup(string _in = default, string _out = default)
        {
            this.In = _in;
            this.Out = _out;
        }

        /// <summary>
        /// Team key that was called in as the backup.
        /// </summary>
        /// <value>Team key that was called in as the backup.</value>
        [DataMember(Name = "in", EmitDefaultValue = false)]
        public string In { get; set; }

        /// <summary>
        /// Team key that was replaced by the backup team.
        /// </summary>
        /// <value>Team key that was replaced by the backup team.</value>
        [DataMember(Name = "out", EmitDefaultValue = false)]
        public string Out { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EliminationAllianceBackup {\n");
            sb.Append("  In: ").Append(In).Append("\n");
            sb.Append("  Out: ").Append(Out).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonSerializer.Serialize(this,this.GetType());
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EliminationAllianceBackup);
        }

        /// <summary>
        /// Returns true if EliminationAllianceBackup instances are equal
        /// </summary>
        /// <param name="input">Instance of EliminationAllianceBackup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EliminationAllianceBackup input)
        {
            if (input == null)
                return false;

            return
                (
                    this.In == input.In ||
                    (this.In != null &&
                    this.In.Equals(input.In))
                ) &&
                (
                    this.Out == input.Out ||
                    (this.Out != null &&
                    this.Out.Equals(input.Out))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.In != null)
                    hashCode = hashCode * 59 + this.In.GetHashCode();
                if (this.Out != null)
                    hashCode = hashCode * 59 + this.Out.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
