/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TBAAPI.V3Client.Model;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
/// <summary>
/// MatchScoreBreakdown2018Alliance
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="MatchScoreBreakdown2018Alliance" /> class.
/// </remarks>
/// <param name="adjustPoints">adjustPoints.</param>
/// <param name="autoOwnershipPoints">autoOwnershipPoints.</param>
/// <param name="autoPoints">autoPoints.</param>
/// <param name="autoQuestRankingPoint">autoQuestRankingPoint.</param>
/// <param name="autoRobot1">autoRobot1.</param>
/// <param name="autoRobot2">autoRobot2.</param>
/// <param name="autoRobot3">autoRobot3.</param>
/// <param name="autoRunPoints">autoRunPoints.</param>
/// <param name="autoScaleOwnershipSec">autoScaleOwnershipSec.</param>
/// <param name="autoSwitchAtZero">autoSwitchAtZero.</param>
/// <param name="autoSwitchOwnershipSec">autoSwitchOwnershipSec.</param>
/// <param name="endgamePoints">endgamePoints.</param>
/// <param name="endgameRobot1">endgameRobot1.</param>
/// <param name="endgameRobot2">endgameRobot2.</param>
/// <param name="endgameRobot3">endgameRobot3.</param>
/// <param name="faceTheBossRankingPoint">faceTheBossRankingPoint.</param>
/// <param name="foulCount">foulCount.</param>
/// <param name="foulPoints">foulPoints.</param>
/// <param name="rp">rp.</param>
/// <param name="techFoulCount">techFoulCount.</param>
/// <param name="teleopOwnershipPoints">teleopOwnershipPoints.</param>
/// <param name="teleopPoints">teleopPoints.</param>
/// <param name="teleopScaleBoostSec">teleopScaleBoostSec.</param>
/// <param name="teleopScaleForceSec">teleopScaleForceSec.</param>
/// <param name="teleopScaleOwnershipSec">teleopScaleOwnershipSec.</param>
/// <param name="teleopSwitchBoostSec">teleopSwitchBoostSec.</param>
/// <param name="teleopSwitchForceSec">teleopSwitchForceSec.</param>
/// <param name="teleopSwitchOwnershipSec">teleopSwitchOwnershipSec.</param>
/// <param name="totalPoints">totalPoints.</param>
/// <param name="vaultBoostPlayed">vaultBoostPlayed.</param>
/// <param name="vaultBoostTotal">vaultBoostTotal.</param>
/// <param name="vaultForcePlayed">vaultForcePlayed.</param>
/// <param name="vaultForceTotal">vaultForceTotal.</param>
/// <param name="vaultLevitatePlayed">vaultLevitatePlayed.</param>
/// <param name="vaultLevitateTotal">vaultLevitateTotal.</param>
/// <param name="vaultPoints">vaultPoints.</param>
/// <param name="tbaGameData">Unofficial TBA-computed value of the FMS provided GameData given to the alliance teams at the start of the match. 3 Character String containing &#x60;L&#x60; and &#x60;R&#x60; only. The first character represents the near switch, the 2nd the scale, and the 3rd the far, opposing, switch from the alliance&#39;s perspective. An &#x60;L&#x60; in a position indicates the platform on the left will be lit for the alliance while an &#x60;R&#x60; will indicate the right platform will be lit for the alliance. See also [WPI Screen Steps](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details)..</param>
[DataContract]
public partial class MatchScoreBreakdown2018Alliance(int adjustPoints = default, int autoOwnershipPoints = default, int autoPoints = default, bool autoQuestRankingPoint = default, string autoRobot1 = default, string autoRobot2 = default, string autoRobot3 = default, int autoRunPoints = default, int autoScaleOwnershipSec = default, bool autoSwitchAtZero = default, int autoSwitchOwnershipSec = default, int endgamePoints = default, string endgameRobot1 = default, string endgameRobot2 = default, string endgameRobot3 = default, bool faceTheBossRankingPoint = default, int foulCount = default, int foulPoints = default, int rp = default, int techFoulCount = default, int teleopOwnershipPoints = default, int teleopPoints = default, int teleopScaleBoostSec = default, int teleopScaleForceSec = default, int teleopScaleOwnershipSec = default, int teleopSwitchBoostSec = default, int teleopSwitchForceSec = default, int teleopSwitchOwnershipSec = default, int totalPoints = default, int vaultBoostPlayed = default, int vaultBoostTotal = default, int vaultForcePlayed = default, int vaultForceTotal = default, int vaultLevitatePlayed = default, int vaultLevitateTotal = default, int vaultPoints = default, string tbaGameData = default) : IEquatable<MatchScoreBreakdown2018Alliance>, IValidatableObject
{

    /// <summary>
    /// Gets or Sets AdjustPoints
    /// </summary>
    [DataMember(Name = "adjustPoints", EmitDefaultValue = false), JsonPropertyName("adjustPoints")]
    public int AdjustPoints { get; set; } = adjustPoints;

    /// <summary>
    /// Gets or Sets AutoOwnershipPoints
    /// </summary>
    [DataMember(Name = "autoOwnershipPoints", EmitDefaultValue = false), JsonPropertyName("autoOwnershipPoints")]
    public int AutoOwnershipPoints { get; set; } = autoOwnershipPoints;

    /// <summary>
    /// Gets or Sets AutoPoints
    /// </summary>
    [DataMember(Name = "autoPoints", EmitDefaultValue = false), JsonPropertyName("autoPoints")]
    public int AutoPoints { get; set; } = autoPoints;

    /// <summary>
    /// Gets or Sets AutoQuestRankingPoint
    /// </summary>
    [DataMember(Name = "autoQuestRankingPoint", EmitDefaultValue = false), JsonPropertyName("autoQuestRankingPoint")]
    public bool AutoQuestRankingPoint { get; set; } = autoQuestRankingPoint;

    /// <summary>
    /// Gets or Sets AutoRobot1
    /// </summary>
    [DataMember(Name = "autoRobot1", EmitDefaultValue = false), JsonPropertyName("autoRobot1")]
    public string AutoRobot1 { get; set; } = autoRobot1;

    /// <summary>
    /// Gets or Sets AutoRobot2
    /// </summary>
    [DataMember(Name = "autoRobot2", EmitDefaultValue = false), JsonPropertyName("autoRobot2")]
    public string AutoRobot2 { get; set; } = autoRobot2;

    /// <summary>
    /// Gets or Sets AutoRobot3
    /// </summary>
    [DataMember(Name = "autoRobot3", EmitDefaultValue = false), JsonPropertyName("autoRobot3")]
    public string AutoRobot3 { get; set; } = autoRobot3;

    /// <summary>
    /// Gets or Sets AutoRunPoints
    /// </summary>
    [DataMember(Name = "autoRunPoints", EmitDefaultValue = false), JsonPropertyName("autoRunPoints")]
    public int AutoRunPoints { get; set; } = autoRunPoints;

    /// <summary>
    /// Gets or Sets AutoScaleOwnershipSec
    /// </summary>
    [DataMember(Name = "autoScaleOwnershipSec", EmitDefaultValue = false), JsonPropertyName("autoScaleOwnershipSec")]
    public int AutoScaleOwnershipSec { get; set; } = autoScaleOwnershipSec;

    /// <summary>
    /// Gets or Sets AutoSwitchAtZero
    /// </summary>
    [DataMember(Name = "autoSwitchAtZero", EmitDefaultValue = false), JsonPropertyName("autoSwitchAtZero")]
    public bool AutoSwitchAtZero { get; set; } = autoSwitchAtZero;

    /// <summary>
    /// Gets or Sets AutoSwitchOwnershipSec
    /// </summary>
    [DataMember(Name = "autoSwitchOwnershipSec", EmitDefaultValue = false), JsonPropertyName("autoSwitchOwnershipSec")]
    public int AutoSwitchOwnershipSec { get; set; } = autoSwitchOwnershipSec;

    /// <summary>
    /// Gets or Sets EndgamePoints
    /// </summary>
    [DataMember(Name = "endgamePoints", EmitDefaultValue = false), JsonPropertyName("endgamePoints")]
    public int EndgamePoints { get; set; } = endgamePoints;

    /// <summary>
    /// Gets or Sets EndgameRobot1
    /// </summary>
    [DataMember(Name = "endgameRobot1", EmitDefaultValue = false), JsonPropertyName("endgameRobot1")]
    public string EndgameRobot1 { get; set; } = endgameRobot1;

    /// <summary>
    /// Gets or Sets EndgameRobot2
    /// </summary>
    [DataMember(Name = "endgameRobot2", EmitDefaultValue = false), JsonPropertyName("endgameRobot2")]
    public string EndgameRobot2 { get; set; } = endgameRobot2;

    /// <summary>
    /// Gets or Sets EndgameRobot3
    /// </summary>
    [DataMember(Name = "endgameRobot3", EmitDefaultValue = false), JsonPropertyName("endgameRobot3")]
    public string EndgameRobot3 { get; set; } = endgameRobot3;

    /// <summary>
    /// Gets or Sets FaceTheBossRankingPoint
    /// </summary>
    [DataMember(Name = "faceTheBossRankingPoint", EmitDefaultValue = false), JsonPropertyName("faceTheBossRankingPoint")]
    public bool FaceTheBossRankingPoint { get; set; } = faceTheBossRankingPoint;

    /// <summary>
    /// Gets or Sets FoulCount
    /// </summary>
    [DataMember(Name = "foulCount", EmitDefaultValue = false), JsonPropertyName("foulCount")]
    public int FoulCount { get; set; } = foulCount;

    /// <summary>
    /// Gets or Sets FoulPoints
    /// </summary>
    [DataMember(Name = "foulPoints", EmitDefaultValue = false), JsonPropertyName("foulPoints")]
    public int FoulPoints { get; set; } = foulPoints;

    /// <summary>
    /// Gets or Sets Rp
    /// </summary>
    [DataMember(Name = "rp", EmitDefaultValue = false), JsonPropertyName("rp")]
    public int Rp { get; set; } = rp;

    /// <summary>
    /// Gets or Sets TechFoulCount
    /// </summary>
    [DataMember(Name = "techFoulCount", EmitDefaultValue = false), JsonPropertyName("techFoulCount")]
    public int TechFoulCount { get; set; } = techFoulCount;

    /// <summary>
    /// Gets or Sets TeleopOwnershipPoints
    /// </summary>
    [DataMember(Name = "teleopOwnershipPoints", EmitDefaultValue = false), JsonPropertyName("teleopOwnershipPoints")]
    public int TeleopOwnershipPoints { get; set; } = teleopOwnershipPoints;

    /// <summary>
    /// Gets or Sets TeleopPoints
    /// </summary>
    [DataMember(Name = "teleopPoints", EmitDefaultValue = false), JsonPropertyName("teleopPoints")]
    public int TeleopPoints { get; set; } = teleopPoints;

    /// <summary>
    /// Gets or Sets TeleopScaleBoostSec
    /// </summary>
    [DataMember(Name = "teleopScaleBoostSec", EmitDefaultValue = false), JsonPropertyName("teleopScaleBoostSec")]
    public int TeleopScaleBoostSec { get; set; } = teleopScaleBoostSec;

    /// <summary>
    /// Gets or Sets TeleopScaleForceSec
    /// </summary>
    [DataMember(Name = "teleopScaleForceSec", EmitDefaultValue = false), JsonPropertyName("teleopScaleForceSec")]
    public int TeleopScaleForceSec { get; set; } = teleopScaleForceSec;

    /// <summary>
    /// Gets or Sets TeleopScaleOwnershipSec
    /// </summary>
    [DataMember(Name = "teleopScaleOwnershipSec", EmitDefaultValue = false), JsonPropertyName("teleopScaleOwnershipSec")]
    public int TeleopScaleOwnershipSec { get; set; } = teleopScaleOwnershipSec;

    /// <summary>
    /// Gets or Sets TeleopSwitchBoostSec
    /// </summary>
    [DataMember(Name = "teleopSwitchBoostSec", EmitDefaultValue = false), JsonPropertyName("teleopSwitchBoostSec")]
    public int TeleopSwitchBoostSec { get; set; } = teleopSwitchBoostSec;

    /// <summary>
    /// Gets or Sets TeleopSwitchForceSec
    /// </summary>
    [DataMember(Name = "teleopSwitchForceSec", EmitDefaultValue = false), JsonPropertyName("teleopSwitchForceSec")]
    public int TeleopSwitchForceSec { get; set; } = teleopSwitchForceSec;

    /// <summary>
    /// Gets or Sets TeleopSwitchOwnershipSec
    /// </summary>
    [DataMember(Name = "teleopSwitchOwnershipSec", EmitDefaultValue = false), JsonPropertyName("teleopSwitchOwnershipSec")]
    public int TeleopSwitchOwnershipSec { get; set; } = teleopSwitchOwnershipSec;

    /// <summary>
    /// Gets or Sets TotalPoints
    /// </summary>
    [DataMember(Name = "totalPoints", EmitDefaultValue = false), JsonPropertyName("totalPoints")]
    public int TotalPoints { get; set; } = totalPoints;

    /// <summary>
    /// Gets or Sets VaultBoostPlayed
    /// </summary>
    [DataMember(Name = "vaultBoostPlayed", EmitDefaultValue = false), JsonPropertyName("vaultBoostPlayed")]
    public int VaultBoostPlayed { get; set; } = vaultBoostPlayed;

    /// <summary>
    /// Gets or Sets VaultBoostTotal
    /// </summary>
    [DataMember(Name = "vaultBoostTotal", EmitDefaultValue = false), JsonPropertyName("vaultBoostTotal")]
    public int VaultBoostTotal { get; set; } = vaultBoostTotal;

    /// <summary>
    /// Gets or Sets VaultForcePlayed
    /// </summary>
    [DataMember(Name = "vaultForcePlayed", EmitDefaultValue = false), JsonPropertyName("vaultForcePlayed")]
    public int VaultForcePlayed { get; set; } = vaultForcePlayed;

    /// <summary>
    /// Gets or Sets VaultForceTotal
    /// </summary>
    [DataMember(Name = "vaultForceTotal", EmitDefaultValue = false), JsonPropertyName("vaultForceTotal")]
    public int VaultForceTotal { get; set; } = vaultForceTotal;

    /// <summary>
    /// Gets or Sets VaultLevitatePlayed
    /// </summary>
    [DataMember(Name = "vaultLevitatePlayed", EmitDefaultValue = false), JsonPropertyName("vaultLevitatePlayed")]
    public int VaultLevitatePlayed { get; set; } = vaultLevitatePlayed;

    /// <summary>
    /// Gets or Sets VaultLevitateTotal
    /// </summary>
    [DataMember(Name = "vaultLevitateTotal", EmitDefaultValue = false), JsonPropertyName("vaultLevitateTotal")]
    public int VaultLevitateTotal { get; set; } = vaultLevitateTotal;

    /// <summary>
    /// Gets or Sets VaultPoints
    /// </summary>
    [DataMember(Name = "vaultPoints", EmitDefaultValue = false), JsonPropertyName("vaultPoints")]
    public int VaultPoints { get; set; } = vaultPoints;

    /// <summary>
    /// Unofficial TBA-computed value of the FMS provided GameData given to the alliance teams at the start of the match. 3 Character String containing &#x60;L&#x60; and &#x60;R&#x60; only. The first character represents the near switch, the 2nd the scale, and the 3rd the far, opposing, switch from the alliance&#39;s perspective. An &#x60;L&#x60; in a position indicates the platform on the left will be lit for the alliance while an &#x60;R&#x60; will indicate the right platform will be lit for the alliance. See also [WPI Screen Steps](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details).
    /// </summary>
    /// <value>Unofficial TBA-computed value of the FMS provided GameData given to the alliance teams at the start of the match. 3 Character String containing &#x60;L&#x60; and &#x60;R&#x60; only. The first character represents the near switch, the 2nd the scale, and the 3rd the far, opposing, switch from the alliance&#39;s perspective. An &#x60;L&#x60; in a position indicates the platform on the left will be lit for the alliance while an &#x60;R&#x60; will indicate the right platform will be lit for the alliance. See also [WPI Screen Steps](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details).</value>
    [DataMember(Name = "tba_gameData", EmitDefaultValue = false), JsonPropertyName("tba_gameData")]
    public string TbaGameData { get; set; } = tbaGameData;

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class MatchScoreBreakdown2018Alliance {\n");
        sb.Append("  AdjustPoints: ").Append(this.AdjustPoints).Append('\n');
        sb.Append("  AutoOwnershipPoints: ").Append(this.AutoOwnershipPoints).Append('\n');
        sb.Append("  AutoPoints: ").Append(this.AutoPoints).Append('\n');
        sb.Append("  AutoQuestRankingPoint: ").Append(this.AutoQuestRankingPoint).Append('\n');
        sb.Append("  AutoRobot1: ").Append(this.AutoRobot1).Append('\n');
        sb.Append("  AutoRobot2: ").Append(this.AutoRobot2).Append('\n');
        sb.Append("  AutoRobot3: ").Append(this.AutoRobot3).Append('\n');
        sb.Append("  AutoRunPoints: ").Append(this.AutoRunPoints).Append('\n');
        sb.Append("  AutoScaleOwnershipSec: ").Append(this.AutoScaleOwnershipSec).Append('\n');
        sb.Append("  AutoSwitchAtZero: ").Append(this.AutoSwitchAtZero).Append('\n');
        sb.Append("  AutoSwitchOwnershipSec: ").Append(this.AutoSwitchOwnershipSec).Append('\n');
        sb.Append("  EndgamePoints: ").Append(this.EndgamePoints).Append('\n');
        sb.Append("  EndgameRobot1: ").Append(this.EndgameRobot1).Append('\n');
        sb.Append("  EndgameRobot2: ").Append(this.EndgameRobot2).Append('\n');
        sb.Append("  EndgameRobot3: ").Append(this.EndgameRobot3).Append('\n');
        sb.Append("  FaceTheBossRankingPoint: ").Append(this.FaceTheBossRankingPoint).Append('\n');
        sb.Append("  FoulCount: ").Append(this.FoulCount).Append('\n');
        sb.Append("  FoulPoints: ").Append(this.FoulPoints).Append('\n');
        sb.Append("  Rp: ").Append(this.Rp).Append('\n');
        sb.Append("  TechFoulCount: ").Append(this.TechFoulCount).Append('\n');
        sb.Append("  TeleopOwnershipPoints: ").Append(this.TeleopOwnershipPoints).Append('\n');
        sb.Append("  TeleopPoints: ").Append(this.TeleopPoints).Append('\n');
        sb.Append("  TeleopScaleBoostSec: ").Append(this.TeleopScaleBoostSec).Append('\n');
        sb.Append("  TeleopScaleForceSec: ").Append(this.TeleopScaleForceSec).Append('\n');
        sb.Append("  TeleopScaleOwnershipSec: ").Append(this.TeleopScaleOwnershipSec).Append('\n');
        sb.Append("  TeleopSwitchBoostSec: ").Append(this.TeleopSwitchBoostSec).Append('\n');
        sb.Append("  TeleopSwitchForceSec: ").Append(this.TeleopSwitchForceSec).Append('\n');
        sb.Append("  TeleopSwitchOwnershipSec: ").Append(this.TeleopSwitchOwnershipSec).Append('\n');
        sb.Append("  TotalPoints: ").Append(this.TotalPoints).Append('\n');
        sb.Append("  VaultBoostPlayed: ").Append(this.VaultBoostPlayed).Append('\n');
        sb.Append("  VaultBoostTotal: ").Append(this.VaultBoostTotal).Append('\n');
        sb.Append("  VaultForcePlayed: ").Append(this.VaultForcePlayed).Append('\n');
        sb.Append("  VaultForceTotal: ").Append(this.VaultForceTotal).Append('\n');
        sb.Append("  VaultLevitatePlayed: ").Append(this.VaultLevitatePlayed).Append('\n');
        sb.Append("  VaultLevitateTotal: ").Append(this.VaultLevitateTotal).Append('\n');
        sb.Append("  VaultPoints: ").Append(this.VaultPoints).Append('\n');
        sb.Append("  TbaGameData: ").Append(this.TbaGameData).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonSerializer.Serialize(this, GetType());

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input) => Equals(input as MatchScoreBreakdown2018Alliance);

    /// <summary>
    /// Returns true if MatchScoreBreakdown2018Alliance instances are equal
    /// </summary>
    /// <param name="input">Instance of MatchScoreBreakdown2018Alliance to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(MatchScoreBreakdown2018Alliance input)
    {
        return input != null
&& (
                this.AdjustPoints == input.AdjustPoints ||
                this.AdjustPoints.Equals(input.AdjustPoints)
            ) &&
            (
                this.AutoOwnershipPoints == input.AutoOwnershipPoints ||
                this.AutoOwnershipPoints.Equals(input.AutoOwnershipPoints)
            ) &&
            (
                this.AutoPoints == input.AutoPoints ||
                this.AutoPoints.Equals(input.AutoPoints)
            ) &&
            (
                this.AutoQuestRankingPoint == input.AutoQuestRankingPoint ||
                this.AutoQuestRankingPoint.Equals(input.AutoQuestRankingPoint)
            ) &&
            (
                this.AutoRobot1 == input.AutoRobot1 ||
                (this.AutoRobot1 != null &&
                this.AutoRobot1.Equals(input.AutoRobot1))
            ) &&
            (
                this.AutoRobot2 == input.AutoRobot2 ||
                (this.AutoRobot2 != null &&
                this.AutoRobot2.Equals(input.AutoRobot2))
            ) &&
            (
                this.AutoRobot3 == input.AutoRobot3 ||
                (this.AutoRobot3 != null &&
                this.AutoRobot3.Equals(input.AutoRobot3))
            ) &&
            (
                this.AutoRunPoints == input.AutoRunPoints ||
                this.AutoRunPoints.Equals(input.AutoRunPoints)
            ) &&
            (
                this.AutoScaleOwnershipSec == input.AutoScaleOwnershipSec ||
                this.AutoScaleOwnershipSec.Equals(input.AutoScaleOwnershipSec)
            ) &&
            (
                this.AutoSwitchAtZero == input.AutoSwitchAtZero ||
                this.AutoSwitchAtZero.Equals(input.AutoSwitchAtZero)
            ) &&
            (
                this.AutoSwitchOwnershipSec == input.AutoSwitchOwnershipSec ||
                this.AutoSwitchOwnershipSec.Equals(input.AutoSwitchOwnershipSec)
            ) &&
            (
                this.EndgamePoints == input.EndgamePoints ||
                this.EndgamePoints.Equals(input.EndgamePoints)
            ) &&
            (
                this.EndgameRobot1 == input.EndgameRobot1 ||
                (this.EndgameRobot1 != null &&
                this.EndgameRobot1.Equals(input.EndgameRobot1))
            ) &&
            (
                this.EndgameRobot2 == input.EndgameRobot2 ||
                (this.EndgameRobot2 != null &&
                this.EndgameRobot2.Equals(input.EndgameRobot2))
            ) &&
            (
                this.EndgameRobot3 == input.EndgameRobot3 ||
                (this.EndgameRobot3 != null &&
                this.EndgameRobot3.Equals(input.EndgameRobot3))
            ) &&
            (
                this.FaceTheBossRankingPoint == input.FaceTheBossRankingPoint ||
                this.FaceTheBossRankingPoint.Equals(input.FaceTheBossRankingPoint)
            ) &&
            (
                this.FoulCount == input.FoulCount ||
                this.FoulCount.Equals(input.FoulCount)
            ) &&
            (
                this.FoulPoints == input.FoulPoints ||
                this.FoulPoints.Equals(input.FoulPoints)
            ) &&
            (
                this.Rp == input.Rp ||
                this.Rp.Equals(input.Rp)
            ) &&
            (
                this.TechFoulCount == input.TechFoulCount ||
                this.TechFoulCount.Equals(input.TechFoulCount)
            ) &&
            (
                this.TeleopOwnershipPoints == input.TeleopOwnershipPoints ||
                this.TeleopOwnershipPoints.Equals(input.TeleopOwnershipPoints)
            ) &&
            (
                this.TeleopPoints == input.TeleopPoints ||
                this.TeleopPoints.Equals(input.TeleopPoints)
            ) &&
            (
                this.TeleopScaleBoostSec == input.TeleopScaleBoostSec ||
                this.TeleopScaleBoostSec.Equals(input.TeleopScaleBoostSec)
            ) &&
            (
                this.TeleopScaleForceSec == input.TeleopScaleForceSec ||
                this.TeleopScaleForceSec.Equals(input.TeleopScaleForceSec)
            ) &&
            (
                this.TeleopScaleOwnershipSec == input.TeleopScaleOwnershipSec ||
                this.TeleopScaleOwnershipSec.Equals(input.TeleopScaleOwnershipSec)
            ) &&
            (
                this.TeleopSwitchBoostSec == input.TeleopSwitchBoostSec ||
                this.TeleopSwitchBoostSec.Equals(input.TeleopSwitchBoostSec)
            ) &&
            (
                this.TeleopSwitchForceSec == input.TeleopSwitchForceSec ||
                this.TeleopSwitchForceSec.Equals(input.TeleopSwitchForceSec)
            ) &&
            (
                this.TeleopSwitchOwnershipSec == input.TeleopSwitchOwnershipSec ||
                this.TeleopSwitchOwnershipSec.Equals(input.TeleopSwitchOwnershipSec)
            ) &&
            (
                this.TotalPoints == input.TotalPoints ||
                this.TotalPoints.Equals(input.TotalPoints)
            ) &&
            (
                this.VaultBoostPlayed == input.VaultBoostPlayed ||
                this.VaultBoostPlayed.Equals(input.VaultBoostPlayed)
            ) &&
            (
                this.VaultBoostTotal == input.VaultBoostTotal ||
                this.VaultBoostTotal.Equals(input.VaultBoostTotal)
            ) &&
            (
                this.VaultForcePlayed == input.VaultForcePlayed ||
                this.VaultForcePlayed.Equals(input.VaultForcePlayed)
            ) &&
            (
                this.VaultForceTotal == input.VaultForceTotal ||
                this.VaultForceTotal.Equals(input.VaultForceTotal)
            ) &&
            (
                this.VaultLevitatePlayed == input.VaultLevitatePlayed ||
                this.VaultLevitatePlayed.Equals(input.VaultLevitatePlayed)
            ) &&
            (
                this.VaultLevitateTotal == input.VaultLevitateTotal ||
                this.VaultLevitateTotal.Equals(input.VaultLevitateTotal)
            ) &&
            (
                this.VaultPoints == input.VaultPoints ||
                this.VaultPoints.Equals(input.VaultPoints)
            ) &&
            (
                this.TbaGameData == input.TbaGameData ||
                (this.TbaGameData != null &&
                this.TbaGameData.Equals(input.TbaGameData))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = (hashCode * 59) + this.AdjustPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoOwnershipPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoQuestRankingPoint.GetHashCode();
            if (this.AutoRobot1 != null)
            {
                hashCode = (hashCode * 59) + this.AutoRobot1.GetHashCode();
            }

            if (this.AutoRobot2 != null)
            {
                hashCode = (hashCode * 59) + this.AutoRobot2.GetHashCode();
            }

            if (this.AutoRobot3 != null)
            {
                hashCode = (hashCode * 59) + this.AutoRobot3.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.AutoRunPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoScaleOwnershipSec.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoSwitchAtZero.GetHashCode();
            hashCode = (hashCode * 59) + this.AutoSwitchOwnershipSec.GetHashCode();
            hashCode = (hashCode * 59) + this.EndgamePoints.GetHashCode();
            if (this.EndgameRobot1 != null)
            {
                hashCode = (hashCode * 59) + this.EndgameRobot1.GetHashCode();
            }

            if (this.EndgameRobot2 != null)
            {
                hashCode = (hashCode * 59) + this.EndgameRobot2.GetHashCode();
            }

            if (this.EndgameRobot3 != null)
            {
                hashCode = (hashCode * 59) + this.EndgameRobot3.GetHashCode();
            }

            hashCode = (hashCode * 59) + this.FaceTheBossRankingPoint.GetHashCode();
            hashCode = (hashCode * 59) + this.FoulCount.GetHashCode();
            hashCode = (hashCode * 59) + this.FoulPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.Rp.GetHashCode();
            hashCode = (hashCode * 59) + this.TechFoulCount.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopOwnershipPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopScaleBoostSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopScaleForceSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopScaleOwnershipSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopSwitchBoostSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopSwitchForceSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TeleopSwitchOwnershipSec.GetHashCode();
            hashCode = (hashCode * 59) + this.TotalPoints.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultBoostPlayed.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultBoostTotal.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultForcePlayed.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultForceTotal.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultLevitatePlayed.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultLevitateTotal.GetHashCode();
            hashCode = (hashCode * 59) + this.VaultPoints.GetHashCode();
            if (this.TbaGameData != null)
            {
                hashCode = (hashCode * 59) + this.TbaGameData.GetHashCode();
            }

            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}
